api:
    security:
        token:
            secret: ${JWT_Secret:123456}
server:
    error:
        include-stacktrace: NEVER
    address: 0.0.0.0
spring:
    application:
        name: CursoSpringBoot - teste
    datasource:
        url: jdbc:postgresql://localhost:5432/hospital_api
        username: postgres
        password: '12345'
        driver-class-name: org.postgresql.Driver

    jpa:
      database-platform: org.hibernate.dialect.PostgreSQLDialect
      hibernate:
        ddl-auto: none


