api:
    security:
        token:
            secret: ${JWT_Secret:123456}
server:
    error:
        include-stacktrace: NEVER
spring:
    application:
        name: CursoSpringBoot - teste
    datasource:
        password: ''
        url: jdbc:mysql://localhost/hospital_api
        username: root
