spring.application.name=CursoSpringBoot - teste
spring.datasource.url=jdbc:mysql://localhost/hospital_api
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=none
flyway.databaseType=mysql

server.error.include-stacktrace=never